file1=open("demo.txt","w")
file1.write("This is file handling")
file1.close()
file2=open("demo.txt","r")
content=file2.read()
print(content)
file2.close()
file3=open("demo.txt","a")
file3.write("\nHow are we doing?")
file3.close()
file4=open("demo.txt","r")
con=file4.read()
print(con)